
export const GET_PRODUCTS = "GET_PRODUCTS";

export const ADD_TO_PREORDER_CART = "ADD_TO_BUY_CART";
export const GET_PREORDER_CART = "GET_BUY_CART";
export const DELETE_PREORDER_CART = "DELETE_PREORDER_CART";

export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART";
export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const REMOVE_FROM_SHOPPING_CART = "REMOVE_FROM_SHOPPING_CART";
export const DELETE_SHOPPING_CART = "DELETE_SHOPPING_CART";
export const UPDATE_SHOPPING_CART = "UPDATE_SHOPPING_CART";
export const ADD_DELIVERY_ADDRESS = "ADD_DELIVERY_ADDRESS";
export const ADD_BILLING_ADDRESS = "ADD_BILLING_ADDRESS";
export const CLEANUP_CART_ADD_STATUS = "CLEANUP_CART_ADD_STATUS";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_DELIVERY_ADDRESS_USER = "ADD_DELIVERY_ADDRESS_USER";
export const ADD_BILLING_ADDRESS_USER = "ADD_BILLING_ADDRESS_USER";

export const SET_PREVIEW = "SET_PREVIEW";

export const SET_ORDER_STATUS = "SET_ORDER_STATUS";
export const CLEANUP_ORDER_STATUS = "CLEANUP_ORDER_STATUS";
export const GET_ORDER_STATUS = "GET_ORDER_STATUS";

export const SET_APP_STATE = "SET_APP_STATE";

export const SET_API_MESSAGE = "SET_API_MESSAGE";
export const CLEANUP_API_MESSAGE = "CLEANUP_API_MESSAGE";

export const SET_MY_ORDER = "SET_MY_ORDER";
export const CLEANUP_MY_ORDER = "CLEANUP_MY_ORDER";


